config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :controllers => {:registrations => 'admins/registrations'}
  devise_scope :admin do
    get '/admin' => "admins#index", :as => :admin_root
    get 'admins', to: 'admins#index'
    get 'admins/show', to: 'admins#show'
    get 'admins/user_activate', to: 'admins#user_activate'
  end

  devise_for :users
  devise_scope :user do
    get '/user' => "users#index", :as => :user_root
    get 'users', to: 'users#index'
    get 'users/download_ovpn_file', to: 'users#download_ovpn_file'
  end

  get 'welcome/index'
  root 'welcome#index'

  get 'pricing', to: 'pricing#index'
  get 'contact', to: 'contact#index'
  get 'faq', to: 'faq#index'
  get '/privacy.txt', :to => redirect('/assets/privacy.txt')

  get 'paypal', to: 'paypal#index'
  post 'paypal/capture', to: 'paypal#capture'
  post 'paypal/create_order', to: 'paypal#create_order'

  get 'payments/create_crypto_wallets', to: 'payments#create_crypto_wallets'
  get 'payments/create_crypto_qrcodes', to: 'payments#create_crypto_qrcodes'
  get 'payments/crypto_price', to: 'payments#crypto_price'
  get '/user/subscribe', to: 'users#subscribe'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer>
<hr class="footer-hr">
<p>made with ruby on rails.</p>
<p><a href="/privacy.txt">privacy</a> | 
  <a href="/usage_terms.txt">usage terms</a> | 
  <a href="/about_us.txt">mission statement</a> | 
  <a href="https://github.com/PanchaTattva" target="blank_">github</a></p>
</footer>
<%= image_tag("sages.png", class: "sages") %>

app/views/layouts/_header.html.erb
<%= image_tag("garuda-header.png", class: "garuda-header") %>

<hr class="header-hr">
<span>
<ul><a href="<%= root_path %>">home</a></ul>
<ul><%= link_to 'pricing', controller: '/pricing' %></ul>
<ul><%= link_to 'faq', controller: '/faq' %></ul>
<ul><%= link_to 'contact', controller: '/contact' %></ul>
<ul> | </ul>
<% if user_signed_in? %>
  <ul><%= link_to "dashboard", controller: 'users' %></ul>
  <ul><%= link_to "logout", destroy_user_session_path, method: :delete %></ul>
<% elsif admin_signed_in? %>
  <ul><%= link_to "admin_dashboard", controller: 'admins' %></ul>
  <ul><%= link_to "admin_logout", destroy_admin_session_path, method: :delete %></ul>
<% else %>
  <ul><%= link_to "login", new_user_session_path %></ul>
  <ul><%= link_to "sign up", new_user_registration_path %></ul>
<% end %>
</span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VPN provider - SA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://www.paypal.com/sdk/js?client-id=AVm16FFwezt03m7PB-a1Jav93krEpF4sGktXjPUiCgUAAqd52QmkPpvCwRjkbYfx1x6DfO7Yt0fOLLrW"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>